version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-setup:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install Yarn package manager
                command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - run:
                name: Install javascript dependencies (using Yarn)
                command: yarn install --ignore-engines
  build-web:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build design tokens for web
                command: yarn web
  deploy-docs:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build design tokens docs
                command: yarn docs
            - persist_to_workspace:
                root: dist
                paths:
                  - tokens.html
            - run:
                name: Install gh-pages dependencies
                command: |
                  yarn global add gh-pages --silent
                  git config user.email "ops@useblu.com.br"
                  git config user.name "Blu"
            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dist dist/tokens.html

workflows:
  build-deploy:
    jobs:
      - build-setup
      - build-web:
        requires:
          - build-setup
      - deploy-docs:
        requires:
          - build-setup
          - build-web
