version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build library
          command: yarn gulp build:lib
      - run:
          name: Build gh-pages
          command: yarn gulp build:doc
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
            - static

  codestyle:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Run linter
          command: yarn lint

  deploy-pkg:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run:
          name: Publish package
          command: |
            # Setup variables
            export VERSION_NUMBER=$(echo $CIRCLE_TAG | awk '{print substr($1,2); }')
            export TAG_NAME=$(echo $VERSION_NUMBER | grep -Po '[a-z]*')
            [ -z "$TAG_NAME" ] && TAG_NAME="latest"
            # Bump and publish
            yarn version --new-version $VERSION_NUMBER --no-git-tag-version --no-commit-hooks
            yarn publish --access public --tag $TAG_NAME

  deploy-doc:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "yarn.lock" }}
      - run:
          name: Configure commit account
          command: |
            git config user.email "ops@useblu.com.br"
            git config user.name "Blu"
      - run:
          name: Deploy static to gh-pages branch
          command: yarn deploy:doc

  trigger-ios:
    executor: node/default
    steps:
      - run:
          name: Update ios pod OceanTokens
          command: |
            curl -u $CIRCLE_CI_TOKEN_OCEAN_DS_IOS -d build_parameters\[CIRCLE_JOB\]=deploy-ocean-tokens https://circleci.com/api/v1.1/project/gh/ocean-ds/ocean-ds-ios/tree/circleci-project-setup

  trigger-android:
    executor: node/default
    steps:
      - run:
          name: Update android lib tokens aar
          command: |
            curl -u $CIRCLE_CI_TOKEN_OCEAN_DS_ANDROID -d build_parameters\[CIRCLE_JOB\]=deploy-ocean-tokens https://circleci.com/api/v1.1/project/gh/ocean-ds/ocean-ds-android/tree/circleci-project-setup

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - gh-pages
      - codestyle:
          requires:
            - build
      - deploy-pkg:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-doc:
          requires:
            - deploy-pkg
          filters:
            tags:
              only: /^v(\d+\.){2}\d+$/
      - trigger-ios:
          requires:
            - deploy-pkg
          filters:
            tags:
              only: /^v(\d+\.){2}\d+$/
      - trigger-android:
          requires:
            - deploy-pkg
          filters:
            tags:
              only: /^v(\d+\.){2}\d+$/
